import '@/styles/globals.css'
import Head from 'next/head'
import Layout from '@/components/Layout'
import { StateContext } from '@/context/stateContext'
import { Toaster } from 'react-hot-toast'

export default function App ({ Component, pageProps }) {
  return (
    <StateContext>
      <Head>
        <title>Bluebyte | Shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.webp' />
      </Head>
      <Layout>
        <Toaster />
        <Component {...pageProps} />
      </Layout>
    </StateContext>

  )
}
